### ISSUE TITLE
上傳檔案要刪除的按鈕會被檔名擋住

### ISSUE THREAD

**Issue by harryhow** [harryhow/keelung#1]

**Comment by harryhow** [comment]
![screen shot 2015-02-11 at 8 26 41 pm](https://cloud.githubusercontent.com/assets/693098/6161827/726a2d40-b22c-11e4-875a-82a35ae39350.png)

是指旁邊的x嘛？

**Comment by harryhow** [comment]
會把左邊的框框調小一點試試看

**Comment by spamore** [comment]
有檔名的時候紅色X會被擋住

**Comment by harryhow** [comment]
可以給我你試的檔案 或是 檔案名稱嘛？

**Comment by spamore** [comment]
我上傳一個看看
2015/2/12 下午3:08 於 "Harry Chen" notifications@github.com 寫道：

**Comment by harryhow** [comment]
1. 改成只顯示檔名，移除前面路徑
      // harry: workaroud for text field overlapping in IE, this will cause cancel button can't use
               $v = strrchr($value,'/');
               $value = substr($v, 0+1, strlen($v));
2. 修改input size from 65 to 45.

**Comment by harryhow** [comment]
@spamore  驗證ie看看可不可以？

**Comment by spamore** [comment]
很好
2015/2/12 下午5:01 於 "Harry Chen" notifications@github.com 寫道：

**Comment by harryhow** [comment]
很好 就可以close了。
