### ISSUE TITLE
意見輸入無法輸入文字

### ISSUE THREAD

**Issue by spamore** [harryhow/keelung#5]
無法出現文字編輯框

**Comment by harryhow** [comment]
能截圖的話 幫我附上圖片 謝謝

**Comment by spamore** [comment]
我在系統裡面不能加好奇怪
2015/2/12 下午3:44 於 "Harry Chen" notifications@github.com 寫道：

**Comment by spamore** [comment]
文字可以輸入了
或許再下面讓民眾可以上傳檔案就好
可行嗎

**Comment by harryhow** [comment]
文字輸入可以了嗎？之前不行的原因是？
上傳檔案應該可以加，我試試看..

**Comment by harryhow** [comment]
另外開issue: 或許再下面讓民眾可以上傳檔案就好
